import { whGet, whPost, whPut, uploadWarehouseFile, openWarehouseFile } from '@/utils/request'

export const warehouseAuthApi = {
  wxLogin: (jsCode, warehouseId, appId) => whPost('/auth/wx-login', { jsCode, warehouseId, appId }),
  passwordLogin: (data) => whPost('/auth/password-login', data),
  passwordRegister: (data) => whPost('/auth/password-register', data),
  passwordSetup: (data) => whPost('/auth/password-setup', data),
  passwordStatus: () => whGet('/auth/password-status'),
  bindPhone: (data) => whPost('/auth/bind-phone', data)
}
export const warehouseApi = {
  uploadFile: uploadWarehouseFile,
  openFile: openWarehouseFile,
  files: () => whGet('/files'),
  submitApply: () => whPost('/apply/submit'),
  customerProgress: (id, data) => whPost(`/customers/${id}/progress`, data),
  acceptCustomer: (id) => whPost(`/customers/${id}/accept`),
  rejectCustomer: (id, reason) => whPost(`/customers/${id}/reject`, { reason }),
  updateContract: (id, data) => whPut(`/contracts/${id}`, data),
  submitContract: (id) => whPost(`/contracts/${id}/submit`),
  settlementLines: (id) => whGet(`/settlement/${id}/lines`),
  apply: () => whGet('/apply'),
  saveApply: (data) => whPut('/apply', data),
  onboarding: () => whGet('/onboarding'),
  attachments: (attachments) => whPost('/apply/attachments', { attachments }),
  dashboard: () => whGet('/dashboard'),
  customers: (params) => whGet('/customers', params),
  orders: (params) => whGet('/orders/page', params),
  erp: () => whGet('/erp'),
  issueSandbox: () => whPost('/erp/issue-sandbox'),
  testOrders: (data) => whPost('/erp/test-orders', data),
  testResults: (params) => whGet('/erp/test-results', params),
  syncLogs: (params) => whGet('/erp/sync-logs', params),
  ping: () => whGet('/erp/ping'),
  bills: (params) => whGet('/bill/page', params),
  billLines: (id) => whGet(`/bill/${id}/lines`),
  confirmBill: (id) => whPost(`/bill/${id}/confirm`),
  disputeBill: (id, reason) => whPost(`/bill/${id}/dispute`, { reason }),
  settlements: (params) => whGet('/settlement/page', params),
  confirmSettlement: (id) => whPost(`/settlement/${id}/confirm`),
  disputeSettlement: (id, reason) => whPost(`/settlement/${id}/dispute`, { reason }),
  contracts: (params) => whGet('/contracts', params),
  createContract: (data) => whPost('/contracts', data),
  agreement: () => whGet('/agreement'),
  uploadAgreement: (file) => whPost('/agreement/upload', { file }),
  notices: (params) => whGet('/notice/page', params),
  noticeUnread: () => whGet('/notice/unread-count'),
  noticeRead: (id) => whPost(`/notice/${id}/read`)
}
