-- 路由-模块映射种子数据
INSERT INTO route_module_mapping (route, module, module_name, is_core, enabled) VALUES
('/building/building/**', 'building', '楼宇管理', 1, 1),
('/building/floor/**', 'building', '楼宇管理', 1, 1),
('/building/project/**', 'building', '楼宇管理', 1, 1),
('/building/room/**', 'building', '楼宇管理', 1, 1),
('/crm/analysis/**', 'crm', '招商管理', 0, 1),
('/crm/channel/**', 'crm', '招商管理', 1, 1),
('/crm/commission/**', 'crm', '招商管理', 1, 1),
('/crm/customer/**', 'crm', '招商管理', 1, 1),
('/crm/follow/**', 'crm', '招商管理', 1, 1),
('/crm/lead/**', 'crm', '招商管理', 1, 1),
('/crm/plan/**', 'crm', '招商管理', 1, 1),
('/tenant/info/**', 'tenant', '租户管理', 1, 1),
('/tenant/message/**', 'tenant', '租户管理', 0, 1),
('/tenant/staff/**', 'tenant', '租户管理', 1, 1),
('/contract/**', 'contract', '合同管理', 1, 1),
('/finance/bill/**', 'finance', '财务管理', 1, 1),
('/finance/checkout-report/**', 'finance', '财务管理', 0, 1),
('/finance/flow/**', 'finance', '财务管理', 0, 1),
('/finance/invoice/**', 'finance', '财务管理', 1, 1),
('/finance/payment/**', 'finance', '财务管理', 1, 1),
('/finance/notice/**', 'finance', '财务管理', 1, 1),
('/finance/receipt/**', 'finance', '财务管理', 1, 1),
('/finance/report/**', 'finance', '财务管理', 0, 1),
('/finance/setting/**', 'finance', '财务管理', 0, 1),
('/finance/receivable/**', 'receivable', '应收管理', 1, 1),
('/property/activity/**', 'property', '物业管理', 0, 1),
('/property/asset/**', 'property', '物业管理', 1, 1),
('/property/check/**', 'property', '物业管理', 1, 1),
('/property/feedback/**', 'property', '物业管理', 0, 1),
('/property/inspection/**', 'property', '物业管理', 1, 1),
('/property/meeting/booking/**', 'property', '物业管理', 0, 1),
('/property/meeting/room/**', 'property', '物业管理', 0, 1),
('/property/patrol/**', 'property', '物业管理', 1, 1),
('/property/survey/**', 'property', '物业管理', 0, 1),
('/property/workorder/**', 'property', '物业管理', 1, 1),
('/energy/stats-api/**', 'energy', '能源管理', 0, 1),
('/energy/meter/**', 'energy', '能源管理', 1, 1),
('/energy/reading/**', 'energy', '能源管理', 1, 1),
('/iot/device/**', 'iot', 'IoT设备', 1, 1),
('/iot/point/**', 'iot', 'IoT设备', 1, 1),
('/iot/alarm/**', 'iot', 'IoT设备', 0, 1),
('/oa/approval/**', 'oa', '办公自动化', 1, 1),
('/oa/attendance/**', 'oa', '办公自动化', 1, 1),
('/oa/document/**', 'oa', '办公自动化', 0, 1),
('/oa/notice/**', 'oa', '办公自动化', 0, 1),
('/oa/flow/**', 'oa', '办公自动化', 1, 1),
('/oa/task/**', 'oa', '办公自动化', 1, 1),
('/service/decoration/**', 'service', '园区服务', 1, 1),
('/service/passcard/**', 'service', '园区服务', 1, 1),
('/service/visitor/**', 'service', '园区服务', 0, 1),
('/acc/access/**', 'acc', '门禁通行', 1, 1),
('/acc/parking/**', 'acc', '门禁通行', 1, 1),
('/am/asset/**', 'am', '资产管理', 1, 1),
('/rsv/booking/**', 'rsv', '预约管理', 1, 1),
('/rsv/resource/**', 'rsv', '预约管理', 0, 1),
('/space/**', 'space', '空间管理', 1, 1),
('/workflow/**', 'workflow', '工作流', 0, 1);

-- 权限种子数据：BI 与建议管理
INSERT INTO sys_menu (menu_name, parent_id, order_num, path, menu_type, perms, icon, visible, status, create_by, create_time) VALUES
('使用度统计', 0, 90, '', 0, '', 'DataLine', 1, 1, 'admin', NOW()),
('管理层视图', (SELECT id FROM sys_menu WHERE menu_name = '使用度统计' LIMIT 1), 1, 'bi/admin', 1, 'bi:admin:view', '', 1, 1, 'admin', NOW()),
('产品团队视图', (SELECT id FROM sys_menu WHERE menu_name = '使用度统计' LIMIT 1), 2, 'bi/product', 1, 'bi:product:view', '', 1, 1, 'admin', NOW()),
('补跑管理', (SELECT id FROM sys_menu WHERE menu_name = '使用度统计' LIMIT 1), 3, '', 2, 'bi:admin:manage', '', 0, 1, 'admin', NOW()),
('建议与反馈', 0, 91, '', 0, '', 'ChatDotRound', 1, 1, 'admin', NOW()),
('我的建议', (SELECT id FROM sys_menu WHERE menu_name = '建议与反馈' LIMIT 1), 1, 'suggestion/mine', 1, '', '', 1, 1, 'admin', NOW()),
('建议管理', (SELECT id FROM sys_menu WHERE menu_name = '建议与反馈' LIMIT 1), 2, 'suggestion/manage', 1, 'suggestion:manage', '', 1, 1, 'admin', NOW());

-- 给管理员角色分配新权限
INSERT INTO sys_role_menu (role_id, menu_id)
SELECT 1, id FROM sys_menu WHERE perms IN ('bi:admin:view', 'bi:admin:manage', 'bi:product:view', 'suggestion:manage');
