import { mount, flushPromises } from '@vue/test-utils'
import { createPinia, setActivePinia } from 'pinia'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import SpatialWorkOrders from '../SpatialWorkOrders.vue'
import { useProjectStore } from '@/stores/project'
import { useAccessStore } from '@/stores/access'

const { page } = vi.hoisted(() => ({ page: vi.fn() }))
vi.mock('@/api/property', () => ({ workOrderApi: { page } }))
const order = { id: 123, projectId: 3, buildingId: 5, floorId: 16, floorPlanFileId: 70, planX: .5, planY: .5, title: '测试故障', status: 3 }
let pinia, project, access
beforeEach(() => {
  pinia = createPinia(); setActivePinia(pinia)
  project = useProjectStore(); project.currentProjectId = 3
  access = useAccessStore(); access.admin = true
  page.mockReset().mockImplementation(async query => ({ total: query.status === 3 ? 1 : 0, records: query.status === 3 ? [order] : [] }))
})
const render = props => mount(SpatialWorkOrders, { props, global: { plugins: [pinia] } })
describe('live spatial work orders', () => {
  it('queries active work in the mapped project, maps only current drawings, and locates on click', async () => {
    page.mockImplementation(async query => ({ total: 3, records: query.status === 3 ? [order, { ...order, id: 124, floorPlanFileId: 1 }, { ...order, id: 125, projectId: 9 }] : [] }))
    const wrapper = render({ floor: 4 }); await flushPromises()
    expect(page.mock.calls.map(([q]) => q.status)).toEqual([1, 2, 3, 4, 7])
    for (const [q] of page.mock.calls) expect(q).toMatchObject({ projectId: 3, buildingId: 5, pageSize: 100 })
    const toggle = wrapper.get('.order-dock-toggle')
    expect(toggle.attributes('aria-expanded')).toBe('false')
    expect(toggle.classes()).toContain('warning')
    expect(toggle.attributes('aria-label')).toContain('待处理 2')
    expect(toggle.text()).toContain('物业工单2项')
    expect(wrapper.find('.order-drawer').exists()).toBe(false)
    expect(wrapper.emitted('points').at(-1)[0]).toHaveLength(1)
    await toggle.trigger('click')
    expect(wrapper.findAll('li')).toHaveLength(1)
    expect(wrapper.text()).toContain('1 条待处理工单需补充定位')
    await wrapper.get('li button').trigger('click')
    expect(wrapper.emitted('locate')[0][0]).toMatchObject({ orderId: 123, floor: 4 })
    expect(toggle.attributes('aria-expanded')).toBe('true')
    expect(wrapper.find('.order-drawer').exists()).toBe(true)
    wrapper.unmount()
  })
  it('shows work across floors even while the model has a selected floor', async () => {
    const lowerOrder = { ...order, id: 124, floorId: 13, floorPlanFileId: 67, title: '一楼待处理工单' }
    page.mockImplementation(async q => ({ total: q.status === 3 ? 2 : 0, records: q.status === 3 ? [order, lowerOrder] : [] }))
    const wrapper = render({ floor: 1 }); await flushPromises()
    await wrapper.get('.order-dock-toggle').trigger('click')
    expect(wrapper.findAll('li')).toHaveLength(2)
    expect(wrapper.get('ul').text()).toContain('4F · 测试故障')
    expect(wrapper.get('ul').text()).toContain('1F · 一楼待处理工单')
    await wrapper.setProps({ floor: 7 })
    expect(wrapper.findAll('li')).toHaveLength(2)
    await wrapper.get('li button').trigger('click')
    expect(wrapper.emitted('locate')[0][0]).toMatchObject({ floor: 4 })
    wrapper.unmount()
  })
  it('counts work without a usable point and provides a calibration hint without a locate action', async () => {
    page.mockImplementation(async q => ({ total: q.status === 1 ? 1 : 0, records: q.status === 1 ? [{ ...order, status: 1, planX: null }] : [] }))
    const wrapper = render(); await flushPromises()
    expect(wrapper.get('.order-dock-toggle').attributes('aria-label')).toContain('待处理 1')
    expect(wrapper.get('.order-dock-toggle').classes()).toContain('warning')
    expect(wrapper.get('.order-dock-toggle').classes()).not.toContain('urgent')
    await wrapper.get('.order-dock-toggle').trigger('click')
    expect(wrapper.text()).toContain('请在工单中补充定位')
    expect(wrapper.find('li button').exists()).toBe(false)
    expect(wrapper.emitted('locate')).toBeUndefined()
    wrapper.unmount()
  })
  it('uses real urgency and SLA fields for red issues, ordinary issues stay yellow, including unmapped records', async () => {
    const records = [order, { ...order, id: 124, urgency: '3' }, { ...order, id: 125, slaState: '1' }, { ...order, id: 126, status: 7 }, { ...order, id: 127, planX: null }, { ...order, id: 128, planX: null, status: '7' }]
    page.mockImplementation(async q => { const matching = records.filter(row => Number(row.status) === q.status); return { total: matching.length, records: matching } })
    const wrapper = render(); await flushPromises()
    expect(wrapper.get('.order-dock-toggle').classes()).toContain('urgent')
    expect(wrapper.get('.order-dock-toggle').classes()).not.toContain('warning')
    expect(wrapper.get('.order-dock-toggle').attributes('aria-label')).toContain('待处理 6 项，紧急 4 项，常规 2 项')
    expect(wrapper.get('.order-dock-toggle').text()).toContain('物业工单6项')
    await wrapper.get('.order-dock-toggle').trigger('click')
    expect(wrapper.get('.severity-pills').text()).toContain('紧急 4')
    expect(wrapper.get('.severity-pills').text()).toContain('常规 2')
    const rows = wrapper.findAll('.order-row')
    expect(rows).toHaveLength(4)
    expect(rows.slice(0, 3).every(row => row.classes().includes('urgent'))).toBe(true)
    expect(rows[3].classes()).toContain('warning')
    expect(wrapper.text()).toContain('其中紧急 1 条')
    expect(wrapper.find('li button svg').exists()).toBe(true)
    wrapper.unmount()
  })
  it('keeps an empty dock calm and explains the empty state after expansion', async () => {
    page.mockResolvedValue({ total: 0, records: [] })
    const wrapper = render(); await flushPromises()
    expect(wrapper.get('.order-dock-toggle').classes()).not.toContain('warning')
    expect(wrapper.get('.order-dock-toggle').classes()).not.toContain('urgent')
    expect(wrapper.get('.order-dock-toggle').attributes('aria-label')).toContain('暂无待处理')
    await wrapper.get('.order-dock-toggle').trigger('click')
    expect(wrapper.get('.order-drawer').text()).toContain('暂无待处理工单。')
    expect(wrapper.find('li').exists()).toBe(false)
    await wrapper.get('section').trigger('keydown', { key: 'Escape' })
    expect(wrapper.get('.order-dock-toggle').attributes('aria-expanded')).toBe('false')
    wrapper.unmount()
  })
  it('discards a late response after the project changes and clears emitted pins', async () => {
    let resolve
    page.mockImplementationOnce(() => new Promise(done => { resolve = done }))
    const wrapper = render(); project.currentProjectId = 8; await flushPromises()
    resolve({ total: 1, records: [order] }); await flushPromises()
    expect(wrapper.emitted('points').at(-1)).toEqual([[]])
    expect(wrapper.find('section').exists()).toBe(false)
    expect(wrapper.emitted('available')).toEqual([[true], [false]])
    expect(page).toHaveBeenCalledTimes(1)
    wrapper.unmount()
  })
  it('does not fetch without existing work-order access', async () => {
    access.admin = false
    const wrapper = render(); await flushPromises()
    expect(page).not.toHaveBeenCalled(); wrapper.unmount()
  })
  it('can locate a completed order explicitly opened from its detail view', async () => {
    page.mockImplementation(async q => ({ total: q.id ? 1 : 0, records: q.id ? [{ ...order, status: 5 }] : [] }))
    const wrapper = render({ requestedOrderId: '123' }); await flushPromises()
    expect(page).toHaveBeenLastCalledWith(expect.objectContaining({ id: 123, projectId: 3, buildingId: 5 }))
    expect(wrapper.emitted('locate')[0][0]).toMatchObject({ orderId: 123, status: '已完成' })
    expect(wrapper.get('.order-dock-toggle').attributes('aria-label')).toContain('暂无待处理')
    expect(wrapper.get('.order-dock-toggle').classes()).not.toContain('warning')
    expect(wrapper.get('.order-dock-toggle').classes()).not.toContain('urgent')
    expect(wrapper.get('.order-dock-toggle').attributes('aria-expanded')).toBe('false')
    await wrapper.get('.order-dock-toggle').trigger('click')
    expect(wrapper.find('li').exists()).toBe(false)
    wrapper.unmount()
  })
  it('reports failed loading and allows retry', async () => {
    page.mockRejectedValueOnce(new Error('offline'))
    const wrapper = render(); await flushPromises()
    expect(wrapper.get('.order-dock-toggle').text()).toContain('加载失败')
    await wrapper.get('.order-dock-toggle').trigger('click')
    expect(wrapper.get('[role="alert"]').text()).toContain('加载失败')
    await wrapper.get('.retry-button').trigger('click'); await flushPromises()
    expect(wrapper.findAll('li')).toHaveLength(1)
    expect(wrapper.get('.order-dock-toggle').attributes('aria-label')).toContain('待处理 1')
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    wrapper.unmount()
  })
  it('keeps the last good pins during a manual refresh and preserves them if refreshing fails', async () => {
    const wrapper = render(); await flushPromises()
    const before = wrapper.emitted('points').length
    await wrapper.get('.order-dock-toggle').trigger('click')
    let rejectRefresh
    page.mockImplementationOnce(() => new Promise((_, reject) => { rejectRefresh = reject }))
    await wrapper.get('header button').trigger('click')
    expect(wrapper.get('.order-dock-toggle').text()).toContain('1项')
    expect(wrapper.findAll('li')).toHaveLength(1)
    expect(wrapper.emitted('points')).toHaveLength(before)
    rejectRefresh(new Error('offline')); await flushPromises()
    expect(wrapper.get('[role="alert"]').text()).toContain('保留上次结果')
    expect(wrapper.findAll('li')).toHaveLength(1)
    expect(wrapper.emitted('points')).toHaveLength(before)
    await wrapper.get('.retry-button').trigger('click'); await flushPromises()
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    expect(wrapper.emitted('points').at(-1)[0]).toHaveLength(1)
    wrapper.unmount()
  })
  it('consumes a requested order once, so refreshing after selecting another point does not jump back', async () => {
    const nextOrder = { ...order, id: 124, floorId: 13, floorPlanFileId: 67 }
    page.mockImplementation(async q => ({ total: q.status === 3 ? 2 : 0, records: q.status === 3 ? [order, nextOrder] : [] }))
    const wrapper = render({ requestedOrderId: '123' }); await flushPromises()
    expect(wrapper.emitted('locate')).toHaveLength(1)
    expect(wrapper.emitted('locate')[0][0]).toMatchObject({ orderId: 123 })
    await wrapper.get('.order-dock-toggle').trigger('click')
    await wrapper.findAll('li button')[1].trigger('click')
    expect(wrapper.emitted('locate').at(-1)[0]).toMatchObject({ orderId: 124 })
    await wrapper.get('header button').trigger('click'); await flushPromises()
    expect(wrapper.emitted('locate')).toHaveLength(2)
    await wrapper.setProps({ requestedOrderId: '124' }); await flushPromises()
    expect(wrapper.emitted('locate')).toHaveLength(3)
    expect(wrapper.emitted('locate').at(-1)[0]).toMatchObject({ orderId: 124 })
    wrapper.unmount()
  })
  it('locates a previously unmatched deep-linked order after its position is corrected and retried', async () => {
    page.mockImplementation(async q => ({ total: q.status === 3 ? 1 : 0, records: q.status === 3 ? [{ ...order, planX: null }] : [] }))
    const wrapper = render({ requestedOrderId: '123' }); await flushPromises()
    expect(wrapper.emitted('locate')).toBeUndefined()
    await wrapper.get('.order-dock-toggle').trigger('click')
    expect(wrapper.get('[role="alert"]').text()).toContain('图纸位置尚未匹配')
    page.mockImplementation(async q => ({ total: q.status === 3 ? 1 : 0, records: q.status === 3 ? [order] : [] }))
    await wrapper.get('.retry-button').trigger('click'); await flushPromises()
    expect(wrapper.find('[role="alert"]').exists()).toBe(false)
    expect(wrapper.emitted('locate')).toHaveLength(1)
    expect(wrapper.emitted('locate')[0][0]).toMatchObject({ orderId: 123, floor: 4 })
    await wrapper.get('header button').trigger('click'); await flushPromises()
    expect(wrapper.emitted('locate')).toHaveLength(1)
    wrapper.unmount()
  })
  it('does not inflate the pending count when a response repeats the same order', async () => {
    page.mockImplementation(async q => ({ total: q.status === 3 ? 2 : 0, records: q.status === 3 ? [order, order] : [] }))
    const wrapper = render(); await flushPromises()
    expect(wrapper.get('.order-dock-toggle').attributes('aria-label')).toContain('待处理 1')
    await wrapper.get('.order-dock-toggle').trigger('click')
    expect(wrapper.findAll('li')).toHaveLength(1)
    wrapper.unmount()
  })
  it('labels a capped result as a partial count instead of presenting it as the full total', async () => {
    page.mockImplementation(async q => ({ total: q.status === 3 ? 1200 : 0, records: q.status === 3 ? Array.from({ length: 10 }, (_, i) => ({ ...order, id: q.pageNo * 100 + i })) : [] }))
    const wrapper = render(); await flushPromises()
    expect(page.mock.calls.filter(([q]) => q.status === 3)).toHaveLength(10)
    expect(wrapper.get('.order-dock-toggle').text()).toContain('100+项')
    await wrapper.get('.order-dock-toggle').trigger('click')
    expect(wrapper.text()).toContain('当前显示部分工单')
    wrapper.unmount()
  })
  it('shows the selected order with drawing and open actions, and reports live counts', async () => {
    const urgent = { ...order, id: 124, urgency: 3, title: '紧急漏水', assignee: '王师傅' }
    page.mockImplementation(async q => ({ total: q.status === 3 ? 2 : 0, records: q.status === 3 ? [order, urgent] : [] }))
    const wrapper = render({ selectedOrderId: 124 }); await flushPromises()
    expect(wrapper.emitted('summary').at(-1)[0]).toEqual({ active: 2, urgent: 1, truncated: false })
    wrapper.vm.expand(); await flushPromises()
    const selected = wrapper.get('.order-selected')
    expect(selected.text()).toContain('紧急漏水')
    expect(wrapper.get('.order-row.is-selected').text()).toContain('紧急漏水')
    await wrapper.get('[data-testid="order-toggle-plan"]').trigger('click')
    expect(wrapper.emitted('toggle-plan')).toHaveLength(1)
    await wrapper.setProps({ planOpen: true })
    expect(wrapper.get('[data-testid="order-toggle-plan"]').text()).toBe('收起图纸')
    await wrapper.get('[data-testid="order-open"]').trigger('click')
    expect(wrapper.emitted('open-order')[0][0]).toMatchObject({ orderId: 124 })
    wrapper.unmount()
  })
})
