import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import TwinHome from '../TwinHome.vue'

const { route, push, sceneReset, sceneFocus } = vi.hoisted(() => ({ route: { path: '/twin-preview', params: {}, query: {}, meta: { twinPreview: true } }, push: vi.fn(), sceneReset: vi.fn(), sceneFocus: vi.fn() }))
vi.mock('vue-router', () => ({ useRoute: () => route, useRouter: () => ({ push }) }))
vi.mock('../WarehouseScene.vue', () => ({ default: { name: 'WarehouseScene', props: ['floor', 'mode', 'layer', 'focused', 'weather', 'viewpoint', 'rotating', 'markers', 'selectedPoint', 'workOrders'], methods: { reset: sceneReset, focusPoint: sceneFocus }, template: '<div class="mock-scene" />' } }))

describe('warehouse workspace interactions', () => {
  beforeEach(() => { push.mockClear(); sceneReset.mockClear(); sceneFocus.mockClear(); localStorage.clear(); route.params = {}; route.query = {}; route.meta = { twinPreview: true } })
  it('starts orbiting and lets the user pause and resume with the orbit control', async () => {
    const wrapper = mount(TwinHome)
    const orbit = wrapper.get('[aria-label="自动环绕"]')
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    expect(scene.props('rotating')).toBe(true)
    expect(orbit.attributes('aria-pressed')).toBe('true')
    await orbit.trigger('click')
    expect(scene.props('rotating')).toBe(false)
    expect(orbit.attributes('aria-pressed')).toBe('false')
    await orbit.trigger('click')
    expect(scene.props('rotating')).toBe(true)
    wrapper.unmount()
  })
  it('offers sunny and night weather without the removed garden and rain controls', () => {
    const wrapper = mount(TwinHome)
    expect(wrapper.find('[data-testid="view-garden"]').exists()).toBe(false)
    expect(wrapper.find('[data-testid="weather-rain"]').exists()).toBe(false)
    expect(wrapper.findAll('.weather-switch button').map(button => button.text())).toEqual(['晴天', '夜景'])
    wrapper.unmount()
  })
  it('can return to the entrance again after the user has moved the camera', async () => {
    const wrapper = mount(TwinHome)
    await wrapper.get('[data-testid="view-entrance"]').trigger('click')
    sceneReset.mockClear()
    await wrapper.get('[data-testid="view-entrance"]').trigger('click')
    expect(sceneReset).toHaveBeenCalledOnce()
    wrapper.unmount()
  })
  it('changes weather without losing the selected floor and opens the entrance view', async () => {
    const wrapper = mount(TwinHome)
    await wrapper.get('[data-testid="floor-5"]').trigger('click')
    await wrapper.get('[data-testid="weather-night"]').trigger('click')
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    expect(scene.props()).toMatchObject({ weather: 'night', floor: 5 })
    await wrapper.get('[data-testid="view-entrance"]').trigger('click')
    expect(scene.props()).toMatchObject({ viewpoint: 'entrance', mode: 'exterior', focused: true })
    await wrapper.get('[aria-label="查看全部楼层"]').trigger('click')
    expect(scene.props()).toMatchObject({ viewpoint: 'overview', weather: 'night', floor: null })
    wrapper.unmount()
  })
  it('opens model focus and restores the surrounding operating panels without losing the selected floor', async () => {
    const wrapper = mount(TwinHome)
    await wrapper.get('[data-testid="floor-5"]').trigger('click')
    await wrapper.get('[aria-label="专注查看模型"]').trigger('click')
    expect(wrapper.findComponent({ name: 'WarehouseScene' }).props()).toMatchObject({ floor: 5, focused: true })
    await wrapper.get('[aria-label="恢复运营看板"]').trigger('click')
    expect(wrapper.findComponent({ name: 'WarehouseScene' }).props()).toMatchObject({ floor: 5, focused: false })
    wrapper.unmount()
  })
  it('keeps the floor selector and interior view synchronized', async () => {
    const wrapper = mount(TwinHome)
    await wrapper.get('[data-testid="floor-5"]').trigger('click')
    await wrapper.get('[data-testid="view-interior"]').trigger('click')
    expect(wrapper.findComponent({ name: 'WarehouseScene' }).props()).toMatchObject({ floor: 5, mode: 'interior' })
    expect(wrapper.text()).toContain('演示数据')
    wrapper.unmount()
  })
  it('keeps illustrative pending counts and cards out of the model workspace', () => {
    const wrapper = mount(TwinHome)
    expect(wrapper.findAll('.ops-property, .ops-pending')).toHaveLength(0)
    expect(wrapper.findComponent({ name: 'WarehouseScene' }).props('selectedPoint')).toBeNull()
    wrapper.unmount()
  })
  it('routes a model point into its local module without creating credentials', async () => {
    localStorage.clear()
    const wrapper = mount(TwinHome)
    wrapper.findComponent({ name: 'WarehouseScene' }).vm.$emit('select-point', { id: 'camera-01', module: 'camera', name: '东侧装卸区监控', floor: 1, code: 'CAM-012', status: '演示在线', location: '1F', values: [] })
    await wrapper.vm.$nextTick()
    await wrapper.get('[data-testid="point-open-module"]').trigger('click')
    expect(push).toHaveBeenCalledWith({ path: '/twin-preview/module/camera', query: { floor: '1' } })
    expect(localStorage.getItem('zhyq_token')).toBeNull()
    wrapper.unmount()
  })
  it('opens a real order on its floor, preserves it in plan view, and links back to the order', async () => {
    route.meta = {}
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    scene.vm.$emit('select-point', { id: 'workorder-123', orderId: 123, module: 'property', floor: 4, name: '测试工单', values: [] })
    await wrapper.vm.$nextTick()
    expect(scene.props()).toMatchObject({ floor: 4, layer: 'property', mode: 'interior', rotating: false, focused: true })
    await wrapper.get('.plan-tools-bar button').trigger('click')
    expect(scene.props('viewpoint')).toBe('plan')
    expect(wrapper.get('[aria-label="空间点位详情"]').text()).toContain('真实工单')
    await wrapper.get('[data-testid="point-open-module"]').trigger('click')
    expect(push).toHaveBeenCalledWith({ path: '/property/workorder', query: { highlightId: '123' } })
    wrapper.unmount()
  })
  it('keeps the work-order dock available beside an open detail and focuses successive orders across floors', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    const wrapper = mount(TwinHome, { global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', template: '<button class="mock-order-dock">物业工单</button>' }, FloorPlanViewer: true } } })
    const scene = wrapper.findComponent({ name: 'WarehouseScene' }), dock = wrapper.findComponent({ name: 'SpatialWorkOrders' })
    const first = { id: 'workorder-123', orderId: 123, module: 'property', floor: 1, name: '一楼工单', values: [] }
    const next = { id: 'workorder-124', orderId: 124, module: 'property', floor: 4, name: '四楼工单', values: [] }
    await wrapper.get('[aria-label="显示定位点"]').trigger('click')
    await wrapper.get('.layer-button:nth-of-type(5)').trigger('click')
    dock.vm.$emit('locate', first); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 1, mode: 'interior', markers: true, rotating: false, layer: 'property', selectedPoint: first })
    expect(sceneFocus).toHaveBeenLastCalledWith(first)
    expect(wrapper.get('.spatial-orders-host').isVisible()).toBe(true)
    expect(wrapper.get('[aria-label="空间点位详情"]').text()).toContain('一楼工单')
    dock.vm.$emit('locate', next); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 4, mode: 'interior', focused: true, selectedPoint: next })
    expect(sceneFocus).toHaveBeenLastCalledWith(next)
    expect(sceneFocus).toHaveBeenCalledTimes(2)
    expect(wrapper.get('.spatial-orders-host').isVisible()).toBe(true)
    expect(wrapper.get('[aria-label="空间点位详情"]').text()).toContain('四楼工单')
    wrapper.unmount()
  })
  it('refreshes the selected order without moving the camera until its drawing location changes', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    const wrapper = mount(TwinHome, { global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', template: '<button />' }, FloorPlanViewer: true } } })
    const scene = wrapper.findComponent({ name: 'WarehouseScene' }), dock = wrapper.findComponent({ name: 'SpatialWorkOrders' })
    const first = { id: 'workorder-123', orderId: 123, module: 'property', floor: 1, name: '一楼工单', localPosition: [10, 0, 20], values: [] }
    dock.vm.$emit('locate', first); await flushPromises()
    sceneFocus.mockClear()
    const refreshed = { ...first, status: '处理中' }
    dock.vm.$emit('points', [refreshed]); await flushPromises()
    expect(scene.props('selectedPoint')).toEqual(refreshed)
    expect(sceneFocus).not.toHaveBeenCalled()
    const moved = { ...refreshed, floor: 4, localPosition: [15, 0, 28] }
    dock.vm.$emit('points', [moved]); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 4, selectedPoint: moved })
    expect(sceneFocus).toHaveBeenCalledOnce()
    expect(sceneFocus).toHaveBeenCalledWith(moved)
    dock.vm.$emit('points', []); await flushPromises()
    expect(scene.props('selectedPoint')).toBeNull()
    expect(wrapper.find('[aria-label="空间点位详情"]').exists()).toBe(false)
    wrapper.unmount()
  })
  it('uses the existing protected business module on the real homepage' , async () => {
    route.meta = {}
    const wrapper = mount(TwinHome)
    expect(wrapper.find('.twin-sidebar').exists()).toBe(false)
    expect(wrapper.find('.twin-topbar').exists()).toBe(false)
    wrapper.findComponent({ name: 'WarehouseScene' }).vm.$emit('open-module', { module: 'contract', floor: 3 })
    expect(push).toHaveBeenCalledWith('/contract/list')
    wrapper.unmount()
  })
})
