import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import TwinHome from '../TwinHome.vue'

const { route, push, sceneReset, sceneFocus } = vi.hoisted(() => ({ route: { path: '/twin-preview', params: {}, query: {}, meta: { twinPreview: true } }, push: vi.fn(), sceneReset: vi.fn(), sceneFocus: vi.fn() }))
vi.mock('vue-router', () => ({ useRoute: () => route, useRouter: () => ({ push }) }))
vi.mock('../WarehouseScene.vue', () => ({ default: { name: 'WarehouseScene', props: ['floor', 'mode', 'layers', 'focused', 'weather', 'viewpoint', 'rotating', 'markers', 'selectedPoint', 'workOrders'], methods: { reset: sceneReset, focusPoint: sceneFocus }, template: '<div class="mock-scene" />' } }))

describe('warehouse workspace interactions', () => {
  beforeEach(() => { push.mockClear(); sceneReset.mockClear(); sceneFocus.mockClear(); localStorage.clear(); route.params = {}; route.query = {}; route.meta = { twinPreview: true } })
  it('starts orbiting and lets the user pause and resume with the orbit control', async () => {
    const wrapper = mount(TwinHome)
    const orbit = wrapper.get('[aria-label="自动环绕"]')
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    expect(scene.props('rotating')).toBe(true)
    expect(orbit.attributes('aria-pressed')).toBe('true')
    await orbit.trigger('click')
    expect(scene.props('rotating')).toBe(false)
    expect(orbit.attributes('aria-pressed')).toBe('false')
    await orbit.trigger('click')
    expect(scene.props('rotating')).toBe(true)
    wrapper.unmount()
  })
  it('keeps weather, reality-reference and export controls out of every model view', async () => {
    const wrapper = mount(TwinHome)
    for (const mode of ['exterior', 'exploded', 'interior']) {
      await wrapper.get(`[data-testid="view-${mode}"]`).trigger('click')
      expect(wrapper.findComponent({ name: 'WarehouseScene' }).props('mode')).toBe(mode)
      expect(wrapper.find('.weather-switch, .weather-simulation, .reference-modal').exists()).toBe(false)
      expect(wrapper.text()).not.toMatch(/天气模拟|实景对照|导出模型|晴天|夜景/)
    }
    wrapper.unmount()
  })
  it('groups model controls in one bottom toolbar and keeps the layer popup in its own bottom-right zone', async () => {
    const wrapper = mount(TwinHome)
    const bottom = wrapper.get('.scene-bottom-bar'), toolbar = bottom.get('.model-toolbar'), layerControls = bottom.get('.scene-layer-controls')
    expect(bottom.element.parentElement.classList.contains('twin-content-grid')).toBe(true)
    expect(wrapper.find('.twin-viewport .scene-bottom-bar').exists()).toBe(false)
    for (const selector of ['[data-testid="view-exterior"]', '[data-testid="view-exploded"]', '[data-testid="view-interior"]', '[aria-label="专注查看模型"]', '[data-testid="view-entrance"]', '[aria-label="放大模型"]', '[aria-label="缩小模型"]', '[aria-label="复位视角"]', '[aria-label="自动环绕"]', '[aria-label="全屏查看"]']) expect(toolbar.find(selector).exists()).toBe(true)
    expect(wrapper.find('.environment-bar .view-switch').exists()).toBe(false)
    expect(toolbar.find('[data-testid="layers-toggle"]').exists()).toBe(false)
    expect(layerControls.find('[data-testid="layers-toggle"]').exists()).toBe(true)
    await layerControls.get('[data-testid="layers-toggle"]').trigger('click')
    expect(layerControls.find('.layer-panel').exists()).toBe(true)
    expect(wrapper.find('.twin-viewport .layer-panel').exists()).toBe(false)
    wrapper.findComponent({ name: 'WarehouseScene' }).vm.$emit('select-floor', 3); await flushPromises()
    for (const selector of ['[data-testid="floor-down"]', '[data-testid="floor-up"]', '[data-testid="plan-view"]', '[data-testid="plan-labels"]']) expect(toolbar.find(selector).exists()).toBe(true)
    wrapper.unmount()
  })
  it('can return to the entrance again after the user has moved the camera', async () => {
    const wrapper = mount(TwinHome)
    await wrapper.get('[data-testid="view-entrance"]').trigger('click')
    sceneReset.mockClear()
    await wrapper.get('[data-testid="view-entrance"]').trigger('click')
    expect(sceneReset).toHaveBeenCalledOnce()
    wrapper.unmount()
  })
  it('opens the entrance view without losing the selected floor', async () => {
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    scene.vm.$emit('select-floor', 5); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 5, mode: 'interior' })
    await wrapper.get('[data-testid="view-entrance"]').trigger('click')
    expect(scene.props()).toMatchObject({ viewpoint: 'entrance', mode: 'exterior', focused: true, floor: 5 })
    wrapper.unmount()
  })
  it('opens model focus and restores the surrounding operating panels without losing the selected floor', async () => {
    const wrapper = mount(TwinHome, { attachTo: document.body })
    const panels = wrapper.findAllComponents({ name: 'TwinOperationsPanel' })
    panels[0].vm.$emit('select-floor', 5); await flushPromises()
    expect(panels.every(panel => panel.isVisible())).toBe(true)
    expect(wrapper.get('.twin-kpi-strip').isVisible()).toBe(true)
    await wrapper.get('[aria-label="专注查看模型"]').trigger('click')
    expect(wrapper.findComponent({ name: 'WarehouseScene' }).props()).toMatchObject({ floor: 5, focused: true })
    expect(panels.every(panel => !panel.isVisible())).toBe(true)
    expect(wrapper.get('.twin-kpi-strip').isVisible()).toBe(false)
    await wrapper.get('[aria-label="恢复运营看板"]').trigger('click')
    expect(wrapper.findComponent({ name: 'WarehouseScene' }).props()).toMatchObject({ floor: 5, focused: false })
    expect(panels.every(panel => panel.isVisible())).toBe(true)
    expect(wrapper.get('.twin-kpi-strip').isVisible()).toBe(true)
    wrapper.unmount()
  })
  it('enters a floor clicked on the model and steps between floors inside, down to the basement', async () => {
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    expect(wrapper.find('.floor-picker').exists()).toBe(false)
    scene.vm.$emit('select-floor', 2); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 2, mode: 'interior', focused: true })
    expect(wrapper.get('.scene-floor-label').text()).toBe('2F')
    await wrapper.get('[data-testid="floor-up"]').trigger('click')
    expect(scene.props('floor')).toBe(3)
    for (let i = 0; i < 3; i++) await wrapper.get('[data-testid="floor-down"]').trigger('click')
    expect(scene.props()).toMatchObject({ floor: -1, mode: 'interior' })
    expect(wrapper.get('[data-testid="floor-down"]').attributes('disabled')).toBeDefined()
    expect(wrapper.text()).toContain('演示数据')
    wrapper.unmount()
  })
  it('keeps illustrative pending counts and cards out of the model workspace', () => {
    const wrapper = mount(TwinHome)
    expect(wrapper.findAll('.ops-property, .ops-pending')).toHaveLength(0)
    expect(wrapper.findComponent({ name: 'WarehouseScene' }).props('selectedPoint')).toBeNull()
    wrapper.unmount()
  })
  it('routes a model point into its local module without creating credentials', async () => {
    localStorage.clear()
    const wrapper = mount(TwinHome)
    wrapper.findComponent({ name: 'WarehouseScene' }).vm.$emit('select-point', { id: 'camera-01', module: 'camera', name: '东侧装卸区监控', floor: 1, code: 'CAM-012', status: '演示在线', location: '1F', values: [] })
    await wrapper.vm.$nextTick()
    await wrapper.get('[data-testid="point-open-module"]').trigger('click')
    expect(push).toHaveBeenCalledWith({ path: '/twin-preview/module/camera', query: { floor: '1' } })
    expect(localStorage.getItem('zhyq_token')).toBeNull()
    wrapper.unmount()
  })
  it('opens a real order on its floor, preserves it in plan view, and links back to the order', async () => {
    route.meta = {}
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    scene.vm.$emit('select-point', { id: 'workorder-123', orderId: 123, module: 'property', floor: 4, name: '测试工单', values: [] })
    await wrapper.vm.$nextTick()
    expect(scene.props()).toMatchObject({ floor: 4, mode: 'interior', rotating: false, focused: true })
    expect(scene.props('layers')).toContain('property')
    await wrapper.get('[data-testid="plan-view"]').trigger('click')
    expect(scene.props('viewpoint')).toBe('plan')
    // Without a session there is no work-order panel, so the floating detail still carries the order.
    expect(wrapper.get('[aria-label="空间点位详情"]').text()).toContain('真实工单')
    await wrapper.get('[data-testid="point-open-module"]').trigger('click')
    expect(push).toHaveBeenCalledWith({ path: '/property/workorder', query: { highlightId: '123' } })
    wrapper.unmount()
  })
  it('keeps the work-order data and selected order while focus hides its panel across successive locations', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    const wrapper = mount(TwinHome, { attachTo: document.body, global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', props: ['selectedOrderId', 'planOpen'], template: '<button class="mock-order-dock">物业工单</button>' }, FloorPlanViewer: true } } })
    const scene = wrapper.findComponent({ name: 'WarehouseScene' }), dock = wrapper.findComponent({ name: 'SpatialWorkOrders' })
    const first = { id: 'workorder-123', orderId: 123, module: 'property', floor: 1, name: '一楼工单', values: [] }
    const next = { id: 'workorder-124', orderId: 124, module: 'property', floor: 4, name: '四楼工单', values: [] }
    dock.vm.$emit('points', [first, next]); await flushPromises()
    await wrapper.get('[data-testid="layers-toggle"]').trigger('click')
    await wrapper.get('[data-testid="layer-property"]').trigger('click')
    expect(scene.props('layers')).not.toContain('property')
    dock.vm.$emit('locate', first); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 1, mode: 'interior', markers: true, rotating: false, selectedPoint: first })
    expect(scene.props('layers')).toContain('property')
    expect(sceneFocus).toHaveBeenLastCalledWith(first)
    expect(dock.isVisible()).toBe(false)
    expect(dock.props('selectedOrderId')).toBe(123)
    dock.vm.$emit('locate', next); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 4, mode: 'interior', focused: true, selectedPoint: next })
    expect(sceneFocus).toHaveBeenLastCalledWith(next)
    expect(sceneFocus).toHaveBeenCalledTimes(2)
    expect(dock.isVisible()).toBe(false)
    expect(dock.props('selectedOrderId')).toBe(124)
    expect(scene.props('workOrders')).toEqual([first, next])
    await wrapper.get('[aria-label="恢复运营看板"]').trigger('click')
    expect(dock.isVisible()).toBe(true)
    expect(dock.props('selectedOrderId')).toBe(124)
    expect(scene.props()).toMatchObject({ floor: 4, selectedPoint: next, workOrders: [first, next] })
    wrapper.unmount()
  })
  it('keeps the work-order list and the source drawing open together, with order details in the panel', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    const expand = vi.fn(), collapse = vi.fn()
    const wrapper = mount(TwinHome, { attachTo: document.body, global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', props: ['selectedOrderId', 'planOpen'], methods: { expand, collapse }, template: '<button />' }, FloorPlanViewer: true } } })
    const dock = wrapper.findComponent({ name: 'SpatialWorkOrders' })
    dock.vm.$emit('available', true); dock.vm.$emit('summary', { active: 10, urgent: 2, truncated: false }); await flushPromises()
    expect(wrapper.get('[data-testid="kpi-work-orders"]').text()).toContain('10')
    expect(wrapper.get('[data-testid="kpi-work-orders"]').text()).toContain('紧急 2')
    await wrapper.get('[data-testid="kpi-work-orders"]').trigger('click')
    expect(expand).toHaveBeenCalledOnce()
    const order = { id: 'workorder-123', orderId: 123, module: 'property', floor: 5, name: '五楼工单', values: [], planFileId: 71 }
    dock.vm.$emit('locate', order); await flushPromises()
    expect(expand).toHaveBeenCalledOnce()
    expect(collapse).toHaveBeenCalledOnce()
    expect(dock.isVisible()).toBe(false)
    expect(wrapper.find('[aria-label="空间点位详情"]').exists()).toBe(false)
    await wrapper.get('[aria-label="恢复运营看板"]').trigger('click')
    expect(dock.isVisible()).toBe(true)
    dock.vm.$emit('toggle-plan'); await flushPromises()
    expect(wrapper.find('.plan-source-panel').exists()).toBe(true)
    expect(dock.props()).toMatchObject({ selectedOrderId: 123, planOpen: true })
    expect(expand).toHaveBeenCalledOnce()
    await wrapper.get('[data-testid="plan-source"]').trigger('click')
    expect(wrapper.find('.plan-source-panel').exists()).toBe(false)
    dock.vm.$emit('open-order', order)
    expect(push).toHaveBeenCalledWith({ path: '/property/workorder', query: { highlightId: '123' } })
    wrapper.unmount()
  })
  it('hides the right-rail work orders and chart panels in focus, retaining their instances and data for return', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    vi.spyOn(HTMLElement.prototype, 'clientWidth', 'get').mockImplementation(function () { return this.classList.contains('twin-main') ? 1200 : 0 })
    const collapse = vi.fn()
    const wrapper = mount(TwinHome, { attachTo: document.body, global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', props: ['selectedOrderId', 'planOpen'], data: () => ({ expanded: false }), methods: { expand() { this.expanded = true }, collapse() { collapse(); this.expanded = false } }, template: '<section class="mock-order-dock"><button data-testid="mock-order-toggle" :aria-expanded="expanded" @click="expanded = !expanded">物业工单</button><div v-if="expanded" data-testid="mock-order-drawer">工单列表</div></section>' }, FloorPlanViewer: true } } })
    await flushPromises()
    const dock = wrapper.findComponent({ name: 'SpatialWorkOrders' }), instance = dock.vm, panels = wrapper.findAllComponents({ name: 'TwinOperationsPanel' }), panelIds = panels.map(panel => panel.vm.$.uid), scene = wrapper.findComponent({ name: 'WarehouseScene' })
    const order = { id: 'workorder-123', orderId: 123, module: 'property', floor: 5, name: '待处理工单', values: [] }
    dock.vm.$emit('points', [order]); dock.vm.$emit('available', true); dock.vm.$emit('summary', { active: 1, urgent: 0, truncated: false }); await flushPromises()
    panels[0].vm.$emit('select-floor', 5); await flushPromises()
    expect(wrapper.find('.rail-orders-slot .mock-order-dock').exists()).toBe(true)
    expect(wrapper.find('.spatial-orders-host .mock-order-dock').exists()).toBe(false)
    expect(dock.isVisible()).toBe(true)
    expect(wrapper.get('[data-testid="kpi-work-orders"]').text()).toContain('1')
    await dock.get('[data-testid="mock-order-toggle"]').trigger('click')
    expect(dock.find('[data-testid="mock-order-drawer"]').exists()).toBe(true)
    await wrapper.get('[aria-label="专注查看模型"]').trigger('click')
    expect(dock.isVisible()).toBe(false)
    expect(panels.every(panel => !panel.isVisible())).toBe(true)
    expect(wrapper.get('.twin-kpi-strip').isVisible()).toBe(false)
    expect(collapse).toHaveBeenCalledOnce()
    expect(dock.find('[data-testid="mock-order-drawer"]').exists()).toBe(false)
    expect(scene.props()).toMatchObject({ floor: 5, focused: true, markers: true, workOrders: [order] })
    await wrapper.get('[aria-label="恢复运营看板"]').trigger('click')
    expect(dock.isVisible()).toBe(true)
    expect(panels.every(panel => panel.isVisible())).toBe(true)
    expect(wrapper.get('.twin-kpi-strip').isVisible()).toBe(true)
    expect(wrapper.get('[data-testid="kpi-work-orders"]').text()).toContain('1')
    expect(wrapper.findComponent({ name: 'SpatialWorkOrders' }).vm).toBe(instance)
    expect(wrapper.findAllComponents({ name: 'TwinOperationsPanel' }).map(panel => panel.vm.$.uid)).toEqual(panelIds)
    expect(dock.find('[data-testid="mock-order-drawer"]').exists()).toBe(false)
    expect(scene.props()).toMatchObject({ floor: 5, focused: false, workOrders: [order] })
    wrapper.unmount(); vi.restoreAllMocks()
  })
  it('toggles business layers independently like Photoshop eyes, without a bottom layer bar', async () => {
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    expect(wrapper.find('.twin-layer-bar').exists()).toBe(false)
    expect(scene.props('layers')).toEqual(['property'])
    await wrapper.get('[data-testid="layers-toggle"]').trigger('click')
    await wrapper.get('[data-testid="layer-camera"]').trigger('click')
    await wrapper.get('[data-testid="layer-fire"]').trigger('click')
    expect(scene.props('layers')).toEqual(['property', 'camera', 'fire'])
    expect(wrapper.get('[data-testid="layer-camera"]').attributes('aria-pressed')).toBe('true')
    await wrapper.get('[data-testid="layer-camera"]').trigger('click')
    expect(scene.props('layers')).toEqual(['property', 'fire'])
    await wrapper.get('.layer-all').trigger('click')
    expect(scene.props('layers')).toHaveLength(6)
    await wrapper.get('.layer-all').trigger('click')
    expect(scene.props('layers')).toEqual([])
    wrapper.unmount()
  })
  it('keeps a chosen work order selected when switching views on its floor', async () => {
    route.meta = {}
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    const order = { id: 'workorder-9', orderId: 9, module: 'property', floor: 4, name: '四楼工单', values: [] }
    scene.vm.$emit('select-point', order); await flushPromises()
    await wrapper.get('[data-testid="view-exploded"]').trigger('click')
    expect(scene.props()).toMatchObject({ mode: 'exploded', floor: 4, selectedPoint: order })
    scene.vm.$emit('select-floor', 6); await flushPromises()
    expect(scene.props()).toMatchObject({ mode: 'interior', floor: 6, selectedPoint: null })
    wrapper.unmount()
  })
  it('refreshes the selected order without moving the camera until its drawing location changes', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    const wrapper = mount(TwinHome, { global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', template: '<button />' }, FloorPlanViewer: true } } })
    const scene = wrapper.findComponent({ name: 'WarehouseScene' }), dock = wrapper.findComponent({ name: 'SpatialWorkOrders' })
    const first = { id: 'workorder-123', orderId: 123, module: 'property', floor: 1, name: '一楼工单', localPosition: [10, 0, 20], values: [] }
    dock.vm.$emit('locate', first); await flushPromises()
    sceneFocus.mockClear()
    const refreshed = { ...first, status: '处理中' }
    dock.vm.$emit('points', [refreshed]); await flushPromises()
    expect(scene.props('selectedPoint')).toEqual(refreshed)
    expect(sceneFocus).not.toHaveBeenCalled()
    const moved = { ...refreshed, floor: 4, localPosition: [15, 0, 28] }
    dock.vm.$emit('points', [moved]); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 4, selectedPoint: moved })
    expect(sceneFocus).toHaveBeenCalledOnce()
    expect(sceneFocus).toHaveBeenCalledWith(moved)
    dock.vm.$emit('points', []); await flushPromises()
    expect(scene.props('selectedPoint')).toBeNull()
    expect(wrapper.find('[aria-label="空间点位详情"]').exists()).toBe(false)
    wrapper.unmount()
  })
  it('uses the existing protected business module on the real homepage' , async () => {
    route.meta = {}
    const wrapper = mount(TwinHome)
    expect(wrapper.find('.twin-sidebar').exists()).toBe(false)
    expect(wrapper.find('.twin-topbar').exists()).toBe(false)
    wrapper.findComponent({ name: 'WarehouseScene' }).vm.$emit('open-module', { module: 'contract', floor: 3 })
    expect(push).toHaveBeenCalledWith('/contract/list')
    wrapper.unmount()
  })
})
