import { flushPromises, mount } from '@vue/test-utils'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import TwinHome from '../TwinHome.vue'

const { route, push, sceneReset, sceneFocus } = vi.hoisted(() => ({ route: { path: '/twin-preview', params: {}, query: {}, meta: { twinPreview: true } }, push: vi.fn(), sceneReset: vi.fn(), sceneFocus: vi.fn() }))
vi.mock('vue-router', () => ({ useRoute: () => route, useRouter: () => ({ push }) }))
vi.mock('../WarehouseScene.vue', () => ({ default: { name: 'WarehouseScene', props: ['floor', 'mode', 'layers', 'focused', 'weather', 'viewpoint', 'rotating', 'markers', 'selectedPoint', 'workOrders'], methods: { reset: sceneReset, focusPoint: sceneFocus }, template: '<div class="mock-scene" />' } }))

describe('warehouse workspace interactions', () => {
  beforeEach(() => { push.mockClear(); sceneReset.mockClear(); sceneFocus.mockClear(); localStorage.clear(); route.params = {}; route.query = {}; route.meta = { twinPreview: true } })
  it('starts orbiting and lets the user pause and resume with the orbit control', async () => {
    const wrapper = mount(TwinHome)
    const orbit = wrapper.get('[aria-label="自动环绕"]')
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    expect(scene.props('rotating')).toBe(true)
    expect(orbit.attributes('aria-pressed')).toBe('true')
    await orbit.trigger('click')
    expect(scene.props('rotating')).toBe(false)
    expect(orbit.attributes('aria-pressed')).toBe('false')
    await orbit.trigger('click')
    expect(scene.props('rotating')).toBe(true)
    wrapper.unmount()
  })
  it('offers sunny and night weather without the removed garden and rain controls', () => {
    const wrapper = mount(TwinHome)
    expect(wrapper.find('[data-testid="view-garden"]').exists()).toBe(false)
    expect(wrapper.find('[data-testid="weather-rain"]').exists()).toBe(false)
    expect(wrapper.findAll('.weather-switch button').map(button => button.text())).toEqual(['晴天', '夜景'])
    wrapper.unmount()
  })
  it('can return to the entrance again after the user has moved the camera', async () => {
    const wrapper = mount(TwinHome)
    await wrapper.get('[data-testid="view-entrance"]').trigger('click')
    sceneReset.mockClear()
    await wrapper.get('[data-testid="view-entrance"]').trigger('click')
    expect(sceneReset).toHaveBeenCalledOnce()
    wrapper.unmount()
  })
  it('changes weather without losing the selected floor and opens the entrance view', async () => {
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    scene.vm.$emit('select-floor', 5); await flushPromises()
    await wrapper.get('[data-testid="weather-night"]').trigger('click')
    expect(scene.props()).toMatchObject({ weather: 'night', floor: 5, mode: 'interior' })
    await wrapper.get('[data-testid="view-entrance"]').trigger('click')
    expect(scene.props()).toMatchObject({ viewpoint: 'entrance', mode: 'exterior', focused: true, weather: 'night', floor: 5 })
    wrapper.unmount()
  })
  it('opens model focus and restores the surrounding operating panels without losing the selected floor', async () => {
    const wrapper = mount(TwinHome)
    wrapper.findComponent({ name: 'TwinOperationsPanel' }).vm.$emit('select-floor', 5); await flushPromises()
    await wrapper.get('[aria-label="专注查看模型"]').trigger('click')
    expect(wrapper.findComponent({ name: 'WarehouseScene' }).props()).toMatchObject({ floor: 5, focused: true })
    await wrapper.get('[aria-label="恢复运营看板"]').trigger('click')
    expect(wrapper.findComponent({ name: 'WarehouseScene' }).props()).toMatchObject({ floor: 5, focused: false })
    wrapper.unmount()
  })
  it('enters a floor clicked on the model and steps between floors inside, down to the basement', async () => {
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    expect(wrapper.find('.floor-picker').exists()).toBe(false)
    scene.vm.$emit('select-floor', 2); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 2, mode: 'interior', focused: true })
    expect(wrapper.get('.dock-floor').text()).toBe('2F')
    await wrapper.get('[data-testid="floor-up"]').trigger('click')
    expect(scene.props('floor')).toBe(3)
    for (let i = 0; i < 3; i++) await wrapper.get('[data-testid="floor-down"]').trigger('click')
    expect(scene.props()).toMatchObject({ floor: -1, mode: 'interior' })
    expect(wrapper.get('[data-testid="floor-down"]').attributes('disabled')).toBeDefined()
    expect(wrapper.text()).toContain('演示数据')
    wrapper.unmount()
  })
  it('keeps illustrative pending counts and cards out of the model workspace', () => {
    const wrapper = mount(TwinHome)
    expect(wrapper.findAll('.ops-property, .ops-pending')).toHaveLength(0)
    expect(wrapper.findComponent({ name: 'WarehouseScene' }).props('selectedPoint')).toBeNull()
    wrapper.unmount()
  })
  it('routes a model point into its local module without creating credentials', async () => {
    localStorage.clear()
    const wrapper = mount(TwinHome)
    wrapper.findComponent({ name: 'WarehouseScene' }).vm.$emit('select-point', { id: 'camera-01', module: 'camera', name: '东侧装卸区监控', floor: 1, code: 'CAM-012', status: '演示在线', location: '1F', values: [] })
    await wrapper.vm.$nextTick()
    await wrapper.get('[data-testid="point-open-module"]').trigger('click')
    expect(push).toHaveBeenCalledWith({ path: '/twin-preview/module/camera', query: { floor: '1' } })
    expect(localStorage.getItem('zhyq_token')).toBeNull()
    wrapper.unmount()
  })
  it('opens a real order on its floor, preserves it in plan view, and links back to the order', async () => {
    route.meta = {}
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    scene.vm.$emit('select-point', { id: 'workorder-123', orderId: 123, module: 'property', floor: 4, name: '测试工单', values: [] })
    await wrapper.vm.$nextTick()
    expect(scene.props()).toMatchObject({ floor: 4, mode: 'interior', rotating: false, focused: true })
    expect(scene.props('layers')).toContain('property')
    await wrapper.get('[data-testid="plan-view"]').trigger('click')
    expect(scene.props('viewpoint')).toBe('plan')
    // Without a session there is no work-order panel, so the floating detail still carries the order.
    expect(wrapper.get('[aria-label="空间点位详情"]').text()).toContain('真实工单')
    await wrapper.get('[data-testid="point-open-module"]').trigger('click')
    expect(push).toHaveBeenCalledWith({ path: '/property/workorder', query: { highlightId: '123' } })
    wrapper.unmount()
  })
  it('keeps the work-order panel open and focuses successive orders across floors', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    const wrapper = mount(TwinHome, { global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', props: ['selectedOrderId', 'planOpen'], template: '<button class="mock-order-dock">物业工单</button>' }, FloorPlanViewer: true } } })
    const scene = wrapper.findComponent({ name: 'WarehouseScene' }), dock = wrapper.findComponent({ name: 'SpatialWorkOrders' })
    const first = { id: 'workorder-123', orderId: 123, module: 'property', floor: 1, name: '一楼工单', values: [] }
    const next = { id: 'workorder-124', orderId: 124, module: 'property', floor: 4, name: '四楼工单', values: [] }
    await wrapper.get('[data-testid="layers-toggle"]').trigger('click')
    await wrapper.get('[data-testid="layer-property"]').trigger('click')
    expect(scene.props('layers')).not.toContain('property')
    dock.vm.$emit('locate', first); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 1, mode: 'interior', markers: true, rotating: false, selectedPoint: first })
    expect(scene.props('layers')).toContain('property')
    expect(sceneFocus).toHaveBeenLastCalledWith(first)
    expect(wrapper.get('.spatial-orders-host').isVisible()).toBe(true)
    expect(dock.props('selectedOrderId')).toBe(123)
    dock.vm.$emit('locate', next); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 4, mode: 'interior', focused: true, selectedPoint: next })
    expect(sceneFocus).toHaveBeenLastCalledWith(next)
    expect(sceneFocus).toHaveBeenCalledTimes(2)
    expect(wrapper.get('.spatial-orders-host').isVisible()).toBe(true)
    expect(dock.props('selectedOrderId')).toBe(124)
    wrapper.unmount()
  })
  it('keeps the work-order list and the source drawing open together, with order details in the panel', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    const expand = vi.fn()
    const wrapper = mount(TwinHome, { global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', props: ['selectedOrderId', 'planOpen'], methods: { expand }, template: '<button />' }, FloorPlanViewer: true } } })
    const dock = wrapper.findComponent({ name: 'SpatialWorkOrders' })
    dock.vm.$emit('available', true); dock.vm.$emit('summary', { active: 10, urgent: 2, truncated: false }); await flushPromises()
    expect(wrapper.get('[data-testid="kpi-work-orders"]').text()).toContain('10')
    expect(wrapper.get('[data-testid="kpi-work-orders"]').text()).toContain('紧急 2')
    await wrapper.get('[data-testid="kpi-work-orders"]').trigger('click')
    expect(expand).toHaveBeenCalledOnce()
    const order = { id: 'workorder-123', orderId: 123, module: 'property', floor: 5, name: '五楼工单', values: [], planFileId: 71 }
    dock.vm.$emit('locate', order); await flushPromises()
    expect(expand).toHaveBeenCalledTimes(2)
    expect(wrapper.find('[aria-label="空间点位详情"]').exists()).toBe(false)
    dock.vm.$emit('toggle-plan'); await flushPromises()
    expect(wrapper.find('.plan-source-panel').exists()).toBe(true)
    expect(dock.props()).toMatchObject({ selectedOrderId: 123, planOpen: true })
    expect(expand).toHaveBeenCalledTimes(2)
    await wrapper.get('[data-testid="plan-source"]').trigger('click')
    expect(wrapper.find('.plan-source-panel').exists()).toBe(false)
    dock.vm.$emit('open-order', order)
    expect(push).toHaveBeenCalledWith({ path: '/property/workorder', query: { highlightId: '123' } })
    wrapper.unmount()
  })
  it('heads the right rail with the work-order panel on a wide dashboard and brings it into the scene when focused', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    vi.spyOn(HTMLElement.prototype, 'clientWidth', 'get').mockImplementation(function () { return this.classList.contains('twin-main') ? 1200 : 0 })
    const wrapper = mount(TwinHome, { attachTo: document.body, global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', props: ['selectedOrderId', 'planOpen'], template: '<button class="mock-order-dock" />' }, FloorPlanViewer: true } } })
    await flushPromises()
    expect(wrapper.find('.rail-orders-slot .mock-order-dock').exists()).toBe(true)
    expect(wrapper.find('.spatial-orders-host .mock-order-dock').exists()).toBe(false)
    expect(wrapper.find('.scene-dock .dock-views').exists()).toBe(true)
    expect(wrapper.find('.environment-bar .view-switch').exists()).toBe(false)
    await wrapper.get('[aria-label="专注查看模型"]').trigger('click')
    expect(wrapper.find('.spatial-orders-host .mock-order-dock').exists()).toBe(true)
    expect(wrapper.find('.rail-orders-slot .mock-order-dock').exists()).toBe(false)
    wrapper.unmount(); vi.restoreAllMocks()
  })
  it('toggles business layers independently like Photoshop eyes, without a bottom layer bar', async () => {
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    expect(wrapper.find('.twin-layer-bar').exists()).toBe(false)
    expect(scene.props('layers')).toEqual(['property'])
    await wrapper.get('[data-testid="layers-toggle"]').trigger('click')
    await wrapper.get('[data-testid="layer-camera"]').trigger('click')
    await wrapper.get('[data-testid="layer-fire"]').trigger('click')
    expect(scene.props('layers')).toEqual(['property', 'camera', 'fire'])
    expect(wrapper.get('[data-testid="layer-camera"]').attributes('aria-pressed')).toBe('true')
    await wrapper.get('[data-testid="layer-camera"]').trigger('click')
    expect(scene.props('layers')).toEqual(['property', 'fire'])
    await wrapper.get('.layer-all').trigger('click')
    expect(scene.props('layers')).toHaveLength(6)
    await wrapper.get('.layer-all').trigger('click')
    expect(scene.props('layers')).toEqual([])
    wrapper.unmount()
  })
  it('keeps a chosen work order selected when switching views on its floor', async () => {
    route.meta = {}
    const wrapper = mount(TwinHome)
    const scene = wrapper.findComponent({ name: 'WarehouseScene' })
    const order = { id: 'workorder-9', orderId: 9, module: 'property', floor: 4, name: '四楼工单', values: [] }
    scene.vm.$emit('select-point', order); await flushPromises()
    await wrapper.get('[data-testid="view-exploded"]').trigger('click')
    expect(scene.props()).toMatchObject({ mode: 'exploded', floor: 4, selectedPoint: order })
    scene.vm.$emit('select-floor', 6); await flushPromises()
    expect(scene.props()).toMatchObject({ mode: 'interior', floor: 6, selectedPoint: null })
    wrapper.unmount()
  })
  it('gathers every model control into the bottom dock and drops the removed buttons', () => {
    const wrapper = mount(TwinHome)
    const dock = wrapper.get('.scene-dock')
    for (const id of ['view-exterior', 'view-exploded', 'view-interior', 'view-entrance', 'layers-toggle']) expect(dock.find(`[data-testid="${id}"]`).exists()).toBe(true)
    expect(dock.find('[aria-label="专注查看模型"]').exists()).toBe(true)
    expect(dock.find('[aria-label="放大模型"]').exists()).toBe(true)
    expect(dock.get('.dock-layers').text()).toContain('业务图层')
    expect(wrapper.get('.environment-bar').findAll('button').map(button => button.text())).toEqual(['晴天', '夜景'])
    expect(wrapper.text()).not.toContain('天气模拟')
    expect(wrapper.text()).not.toContain('实景对照')
    expect(wrapper.text()).not.toContain('导出模型')
    wrapper.unmount()
  })
  it('keeps 专注模型 to the model alone until the user asks for a work order again', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    const expand = vi.fn()
    const wrapper = mount(TwinHome, { global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', props: ['selectedOrderId', 'planOpen'], methods: { expand }, template: '<button class="mock-order-dock" />' }, FloorPlanViewer: true } } })
    const scene = wrapper.findComponent({ name: 'WarehouseScene' }), dock = wrapper.findComponent({ name: 'SpatialWorkOrders' })
    // v-show's inline style; jsdom's computed-style cache misses the change back from display: none.
    const panelShown = () => !(wrapper.get('.spatial-orders-host').attributes('style') || '').includes('display: none')
    dock.vm.$emit('available', true); await flushPromises()
    const order = { id: 'workorder-5', orderId: 5, module: 'property', floor: 3, name: '三楼工单', values: [], planFileId: 69 }
    dock.vm.$emit('locate', order); dock.vm.$emit('toggle-plan'); await flushPromises()
    expect(wrapper.find('.plan-source-panel').exists()).toBe(true)
    await wrapper.get('[aria-label="恢复运营看板"]').trigger('click')
    await wrapper.get('[aria-label="专注查看模型"]').trigger('click')
    expect(scene.props('focused')).toBe(true)
    expect(panelShown()).toBe(false)
    expect(wrapper.find('.plan-source-panel').exists()).toBe(false)
    scene.vm.$emit('select-point', order); await flushPromises()
    expect(panelShown()).toBe(true)
    await wrapper.get('[data-testid="view-entrance"]').trigger('click')
    expect(panelShown()).toBe(false)
    await wrapper.get('[data-testid="kpi-work-orders"]').trigger('click')
    expect(panelShown()).toBe(true)
    wrapper.unmount()
  })
  it('refreshes the selected order without moving the camera until its drawing location changes', async () => {
    route.meta = {}; localStorage.setItem('zhyq_token', 'test-session')
    const wrapper = mount(TwinHome, { global: { stubs: { SpatialWorkOrders: { name: 'SpatialWorkOrders', template: '<button />' }, FloorPlanViewer: true } } })
    const scene = wrapper.findComponent({ name: 'WarehouseScene' }), dock = wrapper.findComponent({ name: 'SpatialWorkOrders' })
    const first = { id: 'workorder-123', orderId: 123, module: 'property', floor: 1, name: '一楼工单', localPosition: [10, 0, 20], values: [] }
    dock.vm.$emit('locate', first); await flushPromises()
    sceneFocus.mockClear()
    const refreshed = { ...first, status: '处理中' }
    dock.vm.$emit('points', [refreshed]); await flushPromises()
    expect(scene.props('selectedPoint')).toEqual(refreshed)
    expect(sceneFocus).not.toHaveBeenCalled()
    const moved = { ...refreshed, floor: 4, localPosition: [15, 0, 28] }
    dock.vm.$emit('points', [moved]); await flushPromises()
    expect(scene.props()).toMatchObject({ floor: 4, selectedPoint: moved })
    expect(sceneFocus).toHaveBeenCalledOnce()
    expect(sceneFocus).toHaveBeenCalledWith(moved)
    dock.vm.$emit('points', []); await flushPromises()
    expect(scene.props('selectedPoint')).toBeNull()
    expect(wrapper.find('[aria-label="空间点位详情"]').exists()).toBe(false)
    wrapper.unmount()
  })
  it('uses the existing protected business module on the real homepage' , async () => {
    route.meta = {}
    const wrapper = mount(TwinHome)
    expect(wrapper.find('.twin-sidebar').exists()).toBe(false)
    expect(wrapper.find('.twin-topbar').exists()).toBe(false)
    wrapper.findComponent({ name: 'WarehouseScene' }).vm.$emit('open-module', { module: 'contract', floor: 3 })
    expect(push).toHaveBeenCalledWith('/contract/list')
    wrapper.unmount()
  })
})
