<template><view class="page-wrap"><view class="card"><view class="wh-title">承接客户</view><view class="wh-note">只展示园区分派给本云仓的客户；拒绝须填写原因。</view><view v-if="loading" class="wh-note">正在读取客户…</view><view v-if="error" class="wh-error">{{ error }}</view><view v-if="!loading && !rows.length && !error" class="wh-note">暂无分派客户，园区分派后会出现在这里。</view><view v-for="c in rows" :key="c.id" class="wh-item"><view class="wh-item-title">{{ c.name }}</view><view class="wh-status">{{ assignmentLabel(c.warehouseAssignmentStatus) }} · {{ STATUS[c.status] || '状态待确认' }}</view><view class="wh-meta">{{ c.contact || '' }} {{ c.phone || '' }}</view><view v-if="c.industry" class="wh-meta">行业：{{ c.industry }}</view><view v-if="c.publicProgress" class="wh-note">最新进度：{{ c.publicProgress }}</view><view v-if="c.warehouseAssignmentStatus===1" class="wh-actions"><button class="wh-secondary" :disabled="busy" @click="accept(c)">确认承接</button><button class="wh-secondary" :disabled="busy" @click="showEditor(c,'reject')">暂不承接</button></view><view v-if="c.warehouseAssignmentStatus===2" class="wh-actions"><button class="wh-secondary" :disabled="busy" @click="showEditor(c,'progress')">更新服务进度</button><button v-if="c.status !== 3" class="wh-secondary" :disabled="busy" @click="draft(c)">起草直签合同</button></view><view v-if="editingId===c.id"><view class="wh-label">{{ editMode==='reject'?'拒绝原因':'对客户推荐伙伴公开的服务进度' }}</view><textarea class="wh-field" v-model="summary" maxlength="500" :disabled="busy" placeholder="请填写具体说明"/><view class="wh-actions"><button class="wh-secondary" :disabled="busy" @click="editingId=null">取消</button><button class="btn" :disabled="busy" :loading="busy" @click="save(c)">提交</button></view></view></view></view><view class="wh-actions wh-pager"><button class="wh-secondary" :disabled="page===1||loading" @click="load(page-1)">上一页</button><view class="wh-note">第 {{ page }} 页 · 共 {{ total }} 条</view><button class="wh-secondary" :disabled="page*20>=total||loading" @click="load(page+1)">下一页</button></view><button v-if="error" class="wh-secondary wh-pager" @click="load(page)">重试</button></view></template>
<script setup>
import {ref} from 'vue'; import {onShow} from '@dcloudio/uni-app'; import {warehouseApi} from '@/api/warehouse'; import {assignmentLabel} from '@/utils/warehouse-ui'
const STATUS={1:'跟进中',2:'已签约',3:'已流失'}
const rows=ref([]),page=ref(1),total=ref(0),loading=ref(false),busy=ref(false),error=ref(''),editingId=ref(null),editMode=ref(''),summary=ref('')
async function load(next=page.value){loading.value=true;error.value='';try{const r=await warehouseApi.customers({pageNo:next,pageSize:20});rows.value=r.records||[];total.value=r.total||0;page.value=next}catch(e){error.value=e.message||'客户读取失败，请重试'}finally{loading.value=false}}
function showEditor(c,mode){editingId.value=c.id;editMode.value=mode;summary.value=mode==='progress'?c.publicProgress||'':''}
async function accept(c){if(busy.value)return;busy.value=true;error.value='';try{await warehouseApi.acceptCustomer(c.id);await load()}catch(e){error.value=e.message||'承接失败，请刷新重试'}finally{busy.value=false}}
async function save(c){if(busy.value)return;if(!summary.value.trim()){error.value='请填写说明';return}busy.value=true;error.value='';try{if(editMode.value==='reject')await warehouseApi.rejectCustomer(c.id,summary.value.trim());else await warehouseApi.customerProgress(c.id,{summary:summary.value.trim()});editingId.value=null;await load()}catch(e){error.value=e.message||'提交失败，请重试'}finally{busy.value=false}}
function draft(c){uni.navigateTo({url:'/pages/warehouse-contracts/index?customerId='+c.id+'&customerName='+encodeURIComponent(c.name||'')})}
onShow(()=>load())
</script><style scoped>@import '../../styles/warehouse.css';</style>
