<template><view class="page-wrap">
  <view class="card"><view class="wh-title">加盟协议</view><view v-if="loading" class="wh-note">正在读取协议…</view><view class="wh-note">{{ agreement.joinStatus === 4 ? '上传双方签署的加盟协议，由园区审核确认上线。' : '加盟协议与客户服务合同分别保存；已上线协议不可自行替换。' }}</view><WarehouseFiles v-model="agreementFiles" :max="1" :readonly="agreement.joinStatus !== 4 || busy" @busy="fileBusy=$event"/><button v-if="agreement.joinStatus === 4" class="btn" :disabled="busy||fileBusy||!agreementFiles.length" :loading="busy" @click="saveAgreement">提交加盟协议</button></view>
  <view class="card"><view class="wh-row"><view class="wh-title">客户服务合同</view><button class="wh-secondary" :disabled="busy" @click="newDraft">起草直签合同</button></view><view class="wh-note">直签合同需上传签署件并提交园区备案审核，商家不能自行使合同生效。</view>
    <view v-if="error" class="wh-error" role="alert">{{ error }}</view>
    <view v-if="editing" class="contract-form">
      <view class="wh-item-title">{{ form.id ? '编辑合同草稿' : '新建直签合同' }}</view>
      <view class="wh-label">已承接客户</view>
      <view v-if="form.id || preselected" class="wh-field">{{ customerName }}</view>
      <picker v-else :range="acceptedCustomers" range-key="name" @change="pickCustomer"><view class="wh-field">{{ customerName || '选择已确认承接的客户' }}</view></picker>
      <view v-if="!acceptedCustomers.length&&!preselected&&!form.id" class="wh-note">暂无可选客户，请先到“承接客户”确认园区分派。</view>
      <view class="wh-label">服务类型</view><picker :range="services" range-key="label" :value="form.serviceType-1" @change="form.serviceType=Number($event.detail.value)+1"><view class="wh-field">{{services[form.serviceType-1]?.label}}</view></picker>
      <view class="wh-label">计费方式</view><picker :range="fees" range-key="label" :value="form.feeModel-1" @change="form.feeModel=Number($event.detail.value)+1"><view class="wh-field">{{fees[form.feeModel-1]?.label}}</view></picker>
      <view class="wh-label">合同开始日期</view><picker mode="date" :value="form.startDate" @change="form.startDate=$event.detail.value"><view class="wh-field">{{form.startDate||'选择日期'}}</view></picker>
      <view class="wh-label">合同结束日期</view><picker mode="date" :value="form.endDate" @change="form.endDate=$event.detail.value"><view class="wh-field">{{form.endDate||'选择日期'}}</view></picker>
      <view class="wh-label">{{ fees[form.feeModel-1]?.unit }}（元）</view><input class="wh-field" v-model="unitPrice" type="digit" placeholder="填写合同约定金额"/>
      <view class="wh-label">保证金（元，可为 0）</view><input class="wh-field" v-model="form.deposit" type="digit" placeholder="0.00"/>
      <view class="wh-label">结算周期</view><picker :range="cycles" :value="form.payCycle-1" @change="form.payCycle=Number($event.detail.value)+1"><view class="wh-field">{{cycles[form.payCycle-1]}}</view></picker>
      <view class="wh-label">合同说明</view><textarea class="wh-field" v-model="form.remark" maxlength="500" placeholder="最多 500 字"/>
      <view class="wh-label">签署件</view><WarehouseFiles v-model="contractFiles" :readonly="busy" @busy="fileBusy=$event"/>
      <view class="wh-actions"><button class="wh-secondary" :disabled="busy||fileBusy" @click="editing=false">取消编辑</button><button class="btn" :disabled="busy||fileBusy" :loading="busy" @click="saveDraft">保存草稿</button></view>
    </view>
    <view v-if="loading" class="wh-note">正在读取合同…</view><view v-if="!loading&&!rows.length&&!error" class="wh-note">暂无服务合同，确认承接客户后可起草直签合同。</view>
    <view v-for="c in rows" :key="c.id" class="wh-item"><view class="wh-item-title">{{c.contractNo}}</view><view class="wh-status">{{CONTRACT[c.status]||'状态待确认'}}</view><view class="wh-meta">{{c.customerName}} · {{c.signMode===2?'云仓直签':'园区签约'}}</view><view class="wh-meta">{{c.startDate||'—'}} 至 {{c.endDate||'—'}}</view><view class="wh-meta">保证金：{{money(c.deposit)}} 元</view><view v-if="c.auditReason" class="wh-error">审核说明：{{c.auditReason}}</view><WarehouseFiles :model-value="parseFiles(c.files)" readonly/><view v-if="c.status===1&&c.signMode===2" class="wh-actions"><button class="wh-secondary" :disabled="busy" @click="edit(c)">编辑草稿</button><button class="wh-secondary" :disabled="busy" @click="submit(c)">提交园区审核</button></view></view>
    <button v-if="error" class="wh-secondary" :disabled="loading" @click="load(page)">刷新重试</button>
  </view><view class="wh-actions wh-pager"><button class="wh-secondary" :disabled="page===1||loading" @click="load(page-1)">上一页</button><view class="wh-note">第 {{page}} 页 · 共 {{total}} 条</view><button class="wh-secondary" :disabled="page*20>=total||loading" @click="load(page+1)">下一页</button></view>
</view></template>
<script setup>
import {reactive,ref,computed} from 'vue';import {onLoad,onShow} from '@dcloudio/uni-app';import {warehouseApi} from '@/api/warehouse';import WarehouseFiles from '@/components/WarehouseFiles.vue';import {CONTRACT,parseFiles,money} from '@/utils/warehouse-ui'
const rows=ref([]),page=ref(1),total=ref(0),loading=ref(false),busy=ref(false),fileBusy=ref(false),error=ref(''),editing=ref(false),preselected=ref(false),unitPrice=ref(''),contractFiles=ref([]),agreementFiles=ref([]),acceptedCustomers=ref([]),selectedName=ref('')
const agreement=reactive({});const empty=()=>({id:null,customerId:null,serviceType:2,feeModel:2,startDate:'',endDate:'',deposit:'0',payCycle:3,remark:''});const form=reactive(empty())
const services=[{label:'仓储'},{label:'代发'},{label:'仓配'}],fees=[{label:'仓租',key:'storage',unit:'仓储费用'},{label:'按票',key:'perOrder',unit:'每票单价'},{label:'按件',key:'perItem',unit:'每件单价'},{label:'包月',key:'monthly',unit:'每月金额'}],cycles=['每周','每半月','每月']
const customerName=computed(()=>selectedName.value||acceptedCustomers.value.find(c=>c.id===form.customerId)?.name||'')
async function load(next=page.value){loading.value=true;error.value='';try{const [r,a,c]=await Promise.all([warehouseApi.contracts({pageNo:next,pageSize:20}),warehouseApi.agreement(),warehouseApi.customers({pageNo:1,pageSize:100})]);rows.value=r.records||[];total.value=r.total||0;page.value=next;Object.assign(agreement,a);agreementFiles.value=a.file?[a.file]:[];acceptedCustomers.value=(c.records||[]).filter(x=>x.warehouseAssignmentStatus===2)}catch(e){error.value=e.message||'合同读取失败，请重试'}finally{loading.value=false}}
function newDraft(){Object.assign(form,empty());preselected.value=false;selectedName.value='';unitPrice.value='';contractFiles.value=[];editing.value=true;error.value=''}
function pickCustomer(e){form.customerId=acceptedCustomers.value[Number(e.detail.value)]?.id;selectedName.value=''}
function edit(c){Object.assign(form,empty(),c);selectedName.value=c.customerName;preselected.value=true;contractFiles.value=parseFiles(c.files);try{unitPrice.value=String(JSON.parse(c.priceTable||'{}')[fees[c.feeModel-1]?.key]??'')}catch{unitPrice.value=''}editing.value=true;error.value=''}
async function saveDraft(){if(busy.value||fileBusy.value)return;error.value='';if(!form.customerId){error.value='请选择已承接客户';return}if(!form.startDate||!form.endDate||form.endDate<=form.startDate){error.value='结束日期必须晚于开始日期';return}if(!/^\d+(\.\d{1,2})?$/.test(String(unitPrice.value))||Number(unitPrice.value)<=0){error.value='请填写大于 0 且最多两位小数的合同单价';return}if(!/^\d+(\.\d{1,2})?$/.test(String(form.deposit))){error.value='保证金需为非负金额，最多两位小数';return}busy.value=true;try{const payload={...form,deposit:Number(form.deposit),priceTable:JSON.stringify({[fees[form.feeModel-1].key]:Number(unitPrice.value)}),files:JSON.stringify(contractFiles.value)};if(form.id)await warehouseApi.updateContract(form.id,payload);else await warehouseApi.createContract(payload);editing.value=false;uni.showToast({title:'草稿已保存',icon:'success'});await load(1)}catch(e){error.value=e.message||'保存失败，请检查填写内容'}finally{busy.value=false}}
async function submit(c){if(busy.value)return;if(!parseFiles(c.files).length){error.value='请先编辑合同并上传签署件';return}busy.value=true;error.value='';try{await warehouseApi.submitContract(c.id);await load(page.value);uni.showToast({title:'已提交园区审核',icon:'success'})}catch(e){error.value=e.message||'提交失败，请重试'}finally{busy.value=false}}
async function saveAgreement(){if(busy.value||fileBusy.value||!agreementFiles.value.length)return;busy.value=true;error.value='';try{await warehouseApi.uploadAgreement('file:'+agreementFiles.value[0].id);uni.showToast({title:'协议已提交',icon:'success'})}catch(e){error.value=e.message||'协议提交失败，请重试'}finally{busy.value=false}}
onLoad(q=>{if(q?.customerId&&/^[1-9]\d*$/.test(q.customerId)){form.customerId=Number(q.customerId);selectedName.value=q.customerName||'';preselected.value=true;editing.value=true}});onShow(()=>load())
</script><style scoped>@import '../../styles/warehouse.css';.contract-form{padding:24rpx 0;border-top:1rpx solid #e6eaf3;border-bottom:1rpx solid #e6eaf3;margin-top:24rpx}</style>
